openapi: 3.0.2
info:
  title: ''
  version: ''
paths:
  /messages/:
    get:
      operationId: listMessages
      description: ''
      parameters:
      - name: user
        required: false
        in: query
        description: user
        schema:
          type: string
      - name: username
        required: false
        in: query
        description: username
        schema:
          type: string
      - name: read
        required: false
        in: query
        description: read
        schema:
          type: string
      - name: sender
        required: false
        in: query
        description: sender
        schema:
          type: string
      - name: sender__username
        required: false
        in: query
        description: sender__username
        schema:
          type: string
      - name: receiver
        required: false
        in: query
        description: receiver
        schema:
          type: string
      - name: receiver__username
        required: false
        in: query
        description: receiver__username
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  properties:
                    id:
                      type: integer
                      readOnly: true
                    sender:
                      type: string
                      readOnly: true
                    receiver:
                      type: integer
                    subject:
                      type: string
                      maxLength: 50
                    message:
                      type: string
                      maxLength: 500
                    read:
                      type: boolean
                    created:
                      type: string
                      format: date-time
                      readOnly: true
                  required:
                  - receiver
                  - subject
                  - message
          description: ''
    post:
      operationId: createMessage
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema: &id001
              properties:
                receiver:
                  type: integer
                subject:
                  type: string
                  maxLength: 50
                message:
                  type: string
                  maxLength: 500
                read:
                  type: boolean
              required:
              - receiver
              - subject
              - message
          application/x-www-form-urlencoded:
            schema: *id001
          multipart/form-data:
            schema: *id001
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  id:
                    type: integer
                    readOnly: true
                  sender:
                    type: string
                    readOnly: true
                  receiver:
                    type: integer
                  subject:
                    type: string
                    maxLength: 50
                  message:
                    type: string
                    maxLength: 500
                  read:
                    type: boolean
                  created:
                    type: string
                    format: date-time
                    readOnly: true
                required:
                - receiver
                - subject
                - message
          description: ''
  /messages/{id}/:
    get:
      operationId: retrieveMessage
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this message.
        schema:
          type: string
      - name: user
        required: false
        in: query
        description: user
        schema:
          type: string
      - name: username
        required: false
        in: query
        description: username
        schema:
          type: string
      - name: read
        required: false
        in: query
        description: read
        schema:
          type: string
      - name: sender
        required: false
        in: query
        description: sender
        schema:
          type: string
      - name: sender__username
        required: false
        in: query
        description: sender__username
        schema:
          type: string
      - name: receiver
        required: false
        in: query
        description: receiver
        schema:
          type: string
      - name: receiver__username
        required: false
        in: query
        description: receiver__username
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  id:
                    type: integer
                    readOnly: true
                  sender:
                    type: string
                    readOnly: true
                  receiver:
                    type: integer
                  subject:
                    type: string
                    maxLength: 50
                  message:
                    type: string
                    maxLength: 500
                  read:
                    type: boolean
                  created:
                    type: string
                    format: date-time
                    readOnly: true
                required:
                - receiver
                - subject
                - message
          description: ''
    put:
      operationId: updateMessage
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this message.
        schema:
          type: string
      - name: user
        required: false
        in: query
        description: user
        schema:
          type: string
      - name: username
        required: false
        in: query
        description: username
        schema:
          type: string
      - name: read
        required: false
        in: query
        description: read
        schema:
          type: string
      - name: sender
        required: false
        in: query
        description: sender
        schema:
          type: string
      - name: sender__username
        required: false
        in: query
        description: sender__username
        schema:
          type: string
      - name: receiver
        required: false
        in: query
        description: receiver
        schema:
          type: string
      - name: receiver__username
        required: false
        in: query
        description: receiver__username
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema: &id002
              properties:
                receiver:
                  type: integer
                subject:
                  type: string
                  maxLength: 50
                message:
                  type: string
                  maxLength: 500
                read:
                  type: boolean
              required:
              - receiver
              - subject
              - message
          application/x-www-form-urlencoded:
            schema: *id002
          multipart/form-data:
            schema: *id002
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  id:
                    type: integer
                    readOnly: true
                  sender:
                    type: string
                    readOnly: true
                  receiver:
                    type: integer
                  subject:
                    type: string
                    maxLength: 50
                  message:
                    type: string
                    maxLength: 500
                  read:
                    type: boolean
                  created:
                    type: string
                    format: date-time
                    readOnly: true
                required:
                - receiver
                - subject
                - message
          description: ''
    patch:
      operationId: partial_updateMessage
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this message.
        schema:
          type: string
      - name: user
        required: false
        in: query
        description: user
        schema:
          type: string
      - name: username
        required: false
        in: query
        description: username
        schema:
          type: string
      - name: read
        required: false
        in: query
        description: read
        schema:
          type: string
      - name: sender
        required: false
        in: query
        description: sender
        schema:
          type: string
      - name: sender__username
        required: false
        in: query
        description: sender__username
        schema:
          type: string
      - name: receiver
        required: false
        in: query
        description: receiver
        schema:
          type: string
      - name: receiver__username
        required: false
        in: query
        description: receiver__username
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema: &id003
              properties:
                receiver:
                  type: integer
                subject:
                  type: string
                  maxLength: 50
                message:
                  type: string
                  maxLength: 500
                read:
                  type: boolean
          application/x-www-form-urlencoded:
            schema: *id003
          multipart/form-data:
            schema: *id003
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  id:
                    type: integer
                    readOnly: true
                  sender:
                    type: string
                    readOnly: true
                  receiver:
                    type: integer
                  subject:
                    type: string
                    maxLength: 50
                  message:
                    type: string
                    maxLength: 500
                  read:
                    type: boolean
                  created:
                    type: string
                    format: date-time
                    readOnly: true
                required:
                - receiver
                - subject
                - message
          description: ''
    delete:
      operationId: destroyMessage
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this message.
        schema:
          type: string
      - name: user
        required: false
        in: query
        description: user
        schema:
          type: string
      - name: username
        required: false
        in: query
        description: username
        schema:
          type: string
      - name: read
        required: false
        in: query
        description: read
        schema:
          type: string
      - name: sender
        required: false
        in: query
        description: sender
        schema:
          type: string
      - name: sender__username
        required: false
        in: query
        description: sender__username
        schema:
          type: string
      - name: receiver
        required: false
        in: query
        description: receiver
        schema:
          type: string
      - name: receiver__username
        required: false
        in: query
        description: receiver__username
        schema:
          type: string
      responses:
        '204':
          description: ''
